#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
compton &
feh --bg-center $(find ~/Pictures/wallpaper -type f | shuf -n 1) &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         1
$HOME/.config/polybar/launch.sh &
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Ulauncher state=floating border=off
